# Algoritmos de optimización - Seminario<br>
**Nombre y Apellidos**: Jim Aguirre Orosco   <br>
**Url**:  https://github.com/jken7/algoritmosoptimizacion <br>
Problema:
> 1. Sesiones de doblaje <br>
>2. Organizar los horarios de partidos de La Liga<br>


Descripción del problema:(copiar enunciado)

Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de grabación independientemente del número de tomas que se graben. No es posible grabar más de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los
servicios de los actores de doblaje sea el menor posible.

....

(*) La respuesta es obligatoria







(*)¿Cuantas posibilidades hay sin tener en cuenta las restricciones?<br>



¿Cuantas posibilidades hay teniendo en cuenta todas las restricciones.




Respuesta:

**Sin Restricciones:**
Si no tuviéramos en cuenta las restricciones, tendríamos que asignar 30 tomas en un número indeterminado de días. Como no hay restricciones sobre cuántas tomas se pueden asignar a un día, podríamos asignar todas las tomas a un solo día o distribuirlas en tantos días como queramos. Por lo tanto, en este caso, el número de posibilidades sería infinito.

**Con Restricciones:**

Para un cálculo muy simplificado, si consideramos solo la restricción de 6 tomas por día, y no consideramos la compatibilidad de tomas, tendríamos:

Para el primer día, hay (30 6)  maneras de asignar 6 tomas.
Para el segundo día, habría (24 6) maneras de asignar 6 de las 24 tomas restantes.
Y así sucesivamente.

Este sería un cálculo muy básico y no considera las restricciones de compatibilidad de tomas y actores ni el hecho de que algunos días podrían tener menos de 6 tomas.
El número exacto de posibilidades, teniendo en cuenta todas las restricciones, es difícil de calcular exactamente y podría requerir un enfoque más avanzado, como técnicas de conteo combinatorio avanzado o incluso métodos computacionales, y aún así podría ser extremadamente grande.

Sin embargo, el objetivo del algoritmo voraz es precisamente evitar tener que explorar todas las posibilidades y proporcionar una solución aproximadamente óptima de manera eficiente.


Modelo para el espacio de soluciones<br>
(*) ¿Cual es la estructura de datos que mejor se adapta al problema? Argumentalo.(Es posible que hayas elegido una al principio y veas la necesidad de cambiar, arguentalo)


1. Matriz (Array 2D) para Representar Participación:
Se ha utilizado una matriz binaria p_ik para representar si el actor i participa en la toma k.
Esta estructura es eficiente para almacenar y acceder a la información de participación de actores en tomas, permitiendo acceder a esta información en tiempo constante.

2. Conjuntos para Tomas Pendientes y Actores Requeridos:
Se han utilizado conjuntos (set) para representar las tomas pendientes de asignar y los actores requeridos en un día.
Los conjuntos permiten agregar, eliminar y verificar la pertenencia de elementos en tiempo promedio constante, lo que es eficiente para el proceso de asignación de tomas a días.

3. Lista de Conjuntos para el Horario:
Se ha utilizado una lista de conjuntos para representar el horario, donde cada conjunto representa las tomas asignadas a un día.
Una lista mantiene un orden de inserción, lo que permite representar los días en el orden en que se van asignando, y cada conjunto dentro de la lista almacena de manera eficiente las tomas asignadas a ese día.

Respuesta

Según el modelo para el espacio de soluciones<br>
(*)¿Cual es la función objetivo?<br>
El objetivo es reducir costos, por ello lo principal sería minimizar el número de veces que el actor va al estudio, para ello se debe maximizar el número de tomas que va ha realizar cuando el actor va al estudio.

<br>
(*)¿Es un problema de maximización o minimización?<br>
Es un problema de minimización debido a que se requiere minimizar los costos.


Respuesta

Diseña un algoritmo para resolver el problema por fuerza bruta:

Un algoritmo de fuerza bruta para este problema implicaría generar todas las posibles asignaciones de tomas a días y luego calcular el valor de la función objetivo para cada asignación, seleccionando la que tenga el valor mínimo. Esto es extremadamente ineficiente y no es recomendable para problemas de tamaño considerable:

**Pasos del Algoritmo de Fuerza Bruta**

**Generar Asignaciones**:
Generar todas las posibles asignaciones de tomas a días, respetando las restricciones del problema (máximo 6 tomas por día y actores coincidentes).

**Calcular Función Objetivo:**
Para cada asignación, calcular el valor de la función objetivo (el número total de asistencias de actores al estudio).

**Seleccionar la Mejor Asignación:**
Seleccionar la asignación que minimiza el valor de la función objetivo.




Respuesta

In [ ]:
from itertools import product, combinations

# Función para resolver el problema de asignación de tomas
def brute_force_schedule(p_ik, max_takes_per_day):
    num_takes, num_actors = p_ik.shape # Número de tomas y de actores
    min_cost = float('inf') # Inicializar el costo mínimo con un valor muy grande
    best_schedule = None # Inicializar la mejor asignación de tomas con None
    
    # Generar todas las combinaciones de tomas para cada día
    for num_days in range(1, (num_takes + max_takes_per_day - 1) // max_takes_per_day + 1): # Número de días
        for schedule in product(combinations(range(num_takes), max_takes_per_day), repeat=num_days): # Combinaciones de tomas
            # Verificar si la asignación de tomas es válida
            if is_valid_schedule(schedule, p_ik): # Si es válida 
                cost = calculate_cost(schedule, p_ik) # Calcular el costo de la asignación de tomas
                if cost < min_cost: # Si el costo es menor al mínimo actual
                    min_cost = cost
                    best_schedule = schedule
                    
    return best_schedule, min_cost

# Función para verificar si una asignación de tomas es válida
def is_valid_schedule(schedule, p_ik):    
    pass

# Función para calcular el costo de una asignación de tomas
def calculate_cost(schedule, p_ik):    
    pass


Calcula la complejidad del algoritmo por fuerza bruta

**Respuesta:**

De manera resumida, la complejidad del algoritmo de fuerza bruta para este problema sería, en el peor de los casos, exponencial en relación al número de tomas y lineal en relación al número de actores, aproximadamente O(2^n * n * A)
. Esto se debe a que se tendrían que explorar todas las posibles combinaciones de asignaciones de tomas a días y, para cada una, calcular el costo asociado, haciendo este enfoque impracticable para instancias moderadas del problema debido a su alta complejidad computacional.

(*)Diseña un algoritmo que mejore la complejidad del algortimo por fuerza bruta. Argumenta porque crees que mejora el algoritmo por fuerza bruta

En este caso, se usará un algoritmo voraz que asigna las tomas de forma iterativa, intentando minimizar el número de días en los que los actores deben asistir al estudio.

Este algoritmo voraz mejora la complejidad del algoritmo por fuerza bruta porque no explora exhaustivamente todo el espacio de soluciones posibles. En cambio, realiza decisiones locales óptimas en cada paso con la esperanza de encontrar una solución globalmente buena. Esto lo hace significativamente más eficiente en comparación con un enfoque de fuerza bruta, especialmente para problemas de mayor tamaño. Además, al considerar el número de actores adicionales requeridos en cada paso, el algoritmo voraz intenta minimizar el número de días en que los actores deben asistir al estudio, alineándose con el objetivo de minimizar el costo total.

Respuesta

In [3]:
import numpy as np
import pandas as pd

# Función para cargar los datos del Excel
def load_data(file_path):
    df = pd.read_excel(file_path, skiprows=1, index_col=0)
    p_ik = df.iloc[:, :-1].to_numpy()
    max_takes_per_day = 6
    return p_ik, max_takes_per_day


# Función de asignación voraz de tomas
def greedy_schedule(p_ik, max_takes_per_day):
    num_takes, num_actors = p_ik.shape # Número de tomas y actores
    pending_takes = set(range(num_takes)) # Tomas pendientes
    schedule = [] # Horario de tomas a realizar por día 

    while pending_takes: # Mientras haya tomas pendientes
        day = set() # Conjunto de tomas del día
        required_actors = set() # Conjunto de actores requeridos

        for _ in range(max_takes_per_day): # Mientras haya espacio en el día
            best_take = None # Mejor toma a agregar
            best_additional_actors = float('inf') # Número de actores adicionales requeridos

            for take in pending_takes: # Para cada toma pendiente
                take_actors = set(np.where(p_ik[take] == 1)[0]) # Actores requeridos por la toma
                additional_actors = len(take_actors - required_actors) # Actores adicionales requeridos

                if additional_actors < best_additional_actors: # Si la toma requiere menos actores adicionales
                    best_take = take # Actualizar la mejor toma
                    best_additional_actors = additional_actors # Actualizar el número de actores adicionales requeridos

            if best_take is None: # Si no hay tomas disponibles
                break # Terminar el día

            day.add(best_take) # Agregar la mejor toma al día
            pending_takes.remove(best_take) # Eliminar la mejor toma de las pendientes
            required_actors.update(np.where(p_ik[best_take] == 1)[0]) # Actualizar los actores requeridos agregando los de la mejor toma si no estaban ya y eliminando los que ya estaban 

        schedule.append(day)  # Agregar el día al horario

    cost = calculate_cost(schedule, p_ik) # Calcular el costo del horario
    return schedule, cost


# Función para calcular el costo
# El costo es el número total de asistencias de actores al estudio
# schedule es una lista de días, donde cada día es un conjunto de tomas
# p_ik es la matriz de actores requeridos por toma
def calculate_cost(schedule, p_ik): # Calcular el costo del horario
    cost = 0 # Costo inicial
    for day in schedule: # Para cada día
        actors_present = set() # Actores presentes
        for take in day: # Para cada toma del día
            actors_present.update(np.where(p_ik[take] == 1)[0]) # Actualizar los actores presentes 
        cost += len(actors_present) # Actualizar el costo sumando el número de actores presentes
    return cost # Regresar el costo

# Ruta al archivo Excel
file_path = "Datos problema doblaje(30 tomas, 10 actores).xlsx"

# Cargar los datos y ejecutar el algoritmo
p_ik, max_takes_per_day = load_data(file_path)
schedule, cost = greedy_schedule(p_ik, max_takes_per_day)

# Mostrar los resultados
print("Asignación Greedy de Tomas:")
for i, day in enumerate(schedule, 1):
    print(f"Día {i}: Tomas {day}")
print(f"Costo Total (Número total de asistencias de actores al estudio): {cost}")


Asignación Greedy de Tomas:
Día 1: Tomas {1, 12, 15, 26, 30, 31}
Día 2: Tomas {13, 16, 17, 18, 22, 23}
Día 3: Tomas {4, 7, 8, 20, 27, 29}
Día 4: Tomas {0, 2, 3, 5, 6, 14}
Día 5: Tomas {9, 10, 11, 19, 25, 28}
Día 6: Tomas {24, 21}
Costo Total (Número total de asistencias de actores al estudio): 33


(*)Calcula la complejidad del algoritmo

**Respuesta:**

El algoritmo realiza un proceso iterativo donde, en cada iteración (correspondiente a un día), selecciona de manera voraz las tomas a asignar, evaluando cada toma pendiente en función de los actores requeridos. 
Este proceso de selección tiene una complejidad aproximadamente cuadrática en el número de tomas y lineal en el número de actores, es decir, O(n^2 * m), donde n es el número de tomas y m es el número de actores.
El algoritmo tiene una complejidad de O(n^2 * m) porque, en el peor caso, cada toma requiere a todos los actores y, en cada iteración, se evalúan todas las tomas pendientes.

Según el problema (y tenga sentido), diseña un juego de datos de entrada aleatorios

Respuesta

In [5]:
import numpy as np

# Parámetros del problema
num_tomas = 30  # Número de Tomas
num_actores = 10  # Número de Actores
prob_participacion = 0.3  # Probabilidad de que un actor participe en una toma

# Inicializar la matriz de participación con ceros
p_ik_random = np.zeros((num_tomas, num_actores), dtype=int)

# Llenar la matriz con participaciones aleatorias
for i in range(num_tomas):
    for k in range(num_actores):
        p_ik_random[i, k] = np.random.rand() < prob_participacion  # 1 con probabilidad prob_participacion, 0 en caso contrario

# Asegurar que cada toma tenga al menos un actor
for i in range(num_tomas):
    if np.sum(p_ik_random[i, :]) == 0:  # Si no hay actores asignados a la toma i
        actor_aleatorio = np.random.randint(num_actores)  # Seleccionar un actor aleatorio
        p_ik_random[i, actor_aleatorio] = 1  # Asignar el actor aleatorio a la toma i

# Mostrar la matriz de participación generada
print(p_ik_random)


[[0 1 0 0 0 0 0 1 0 1]
 [0 1 1 0 0 1 0 0 0 0]
 [0 1 0 0 0 1 0 1 1 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 1 1 0 0 0 1 1 0 1]
 [0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0 0 1]
 [1 1 1 0 1 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 0]
 [0 0 1 1 0 1 1 1 0 0]
 [1 1 0 0 1 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 1 1 1 0 0]
 [0 1 1 0 0 1 0 1 0 0]
 [1 0 1 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 1 0]
 [0 0 1 0 1 0 0 1 1 0]
 [1 0 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 1 0 1 1 0]
 [0 0 0 1 0 1 0 0 0 1]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 1 1]
 [0 0 1 0 1 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 1 1]
 [0 0 0 0 0 0 0 1 1 1]
 [1 1 0 1 1 0 1 0 1 0]]


Aplica el algoritmo al juego de datos generado

Respuesta

In [6]:
# Aplicar el algoritmo greedy al juego de datos generado
random_schedule_result, random_schedule_cost = greedy_schedule(p_ik_random, max_takes_per_day)

# Mostrar los resultados
print("Asignación Greedy de Tomas:")
for i, day in enumerate(random_schedule_result, 1):
    print(f"Día {i}: Tomas {day}")
print(f"Costo Total (Número total de asistencias de actores al estudio): {random_schedule_cost}")

Asignación Greedy de Tomas:
Día 1: Tomas {3, 5, 9, 12, 13, 24}
Día 2: Tomas {0, 6, 7, 16, 18, 21}
Día 3: Tomas {1, 2, 10, 14, 15, 17}
Día 4: Tomas {19, 20, 25, 26, 27, 28}
Día 5: Tomas {4, 8, 11, 22, 23, 29}
Costo Total (Número total de asistencias de actores al estudio): 31


Enumera las referencias que has utilizado(si ha sido necesario) para llevar a cabo el trabajo

Respuesta

Describe brevemente las lineas de como crees que es posible avanzar en el estudio del problema. Ten en cuenta incluso posibles variaciones del problema y/o variaciones al alza del tamaño

**Respuesta:**

El problema planteado, de coordinar el doblaje de una película minimizando los costos asociados a los actores de doblaje, tiene varias líneas posibles de avance y estudio, tanto en la formulación del problema como en las técnicas de solución. Aquí algunos posibles avances:

**Variaciones del Problema:**<br>
-Prioridades entre Tomas: Algunas tomas podrían tener prioridad sobre otras y deberían ser programadas antes. <br>
-Disponibilidad de Actores: Los actores podrían tener restricciones de disponibilidad.<br>
-Costos Variables: Los actores podrían tener diferentes tarifas y/o costos asociados a su participación.<br>
-Multitarea: Considerar si un actor puede participar en la grabación de diferentes tomas simultáneamente si sus personajes no interactúan.<br>